### ISSUE TITLE
N'afficher que les lignes signifiantes dans "détails" (suite à erreur de publication)

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#106]
Aujourd'hui, en cas d'erreur lors de la publication, il est difficile de voir de quoi il retourne car l'info est noyée. 

Exemple :

	

> Traceback (most recent call last):
>   File "/home/.../src/kolekti/publish.py", line 1074, in publish_assembly
>     xassembly = self.parse(self._release_dir + '/sources/' + self._publang + '/assembly/'+ assembly + '.html')
>   File "/home/.../src/kolekti/common.py", line 466, in parse
>     return ET.parse(src,self._xmlparser)
>   File "lxml.etree.pyx", line 3301, in lxml.etree.parse (src/lxml/lxml.etree.c:72453)
>   File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:105915)
>   File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106214)
>   File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105213)
>   File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100163)
>   File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94286)
>   File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95722)
>   File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94789)
> XMLSyntaxError: ID cke_bm_186C already defined, line 1886, column 52

Ici seule la dernière ligne est importante, est-il possible de ne pas afficher les autres ?

**Comment by vbdx** [comment]
S'il est possible de n'afficher que la ou les lignes signifiantes, alors peut-être qu'il sera possible de mettre cette ligne directement dans la fenêtre de publication (plus d'obligation de cliquer sur Détails) ?

Dans le cas ci-dessus, le message dans la fenêtre de publication indique :

> Erreur à la publication
> impossible de lire l'assemblage

Pourrait-on avoir à la place qqchose du genre :

> Erreur à la publication
> Problème de syntaxe dans l'assemblage (ID cke_bm_186C already defined, line 1886, column 52)

**Comment by vbdx** [comment]
A voir si l'aide en ligne peut faire la liste des messages-type avec leur explication et la marche à suivre

**Comment by kolekti** [comment]
Le probleme est que le publication peut ne pas fonctionner pour de multiples raisons, il est difficile d'en faire un liste exhaustive. Le message signifiant pour l'utilisateur n'est pas forcément la dernière ligne de "détail", seul un oeil de développeur peut le détecter. 
Peut être l'erreur de publicatin devrait envoyer un mail automatique avec les erreurs de publication sans afficher les détails pour l'utilisateur.

**Comment by vbdx** [comment]
Sans aller jusqu'à une liste exhaustive de tous les cas de figure, n'est-il pas possible de dire :

- à quel moment (étape du processus) l'erreur est apparue
- sur quel fichier
- et éventuellement la nature de l'erreur (absence de fichier, fichier présent mais non valide, fichier présent mais ne comportant pas l'info recherchée, etc.)

Ensuite, je suis pour ne pas afficher les détails dans l'interface (ça fait peur), et de les rendre accessibles dans les logs plutôt que par un envoi de mail

**Comment by vbdx** [comment]
A court terme, on va préciser dans le message de premier niveau (Erreur lors de la publication") les sources possibles d'erreur
